/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tickets visible to the caller's organisation */
        get: operations["listTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one ticket visible to the caller's organisation */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TicketSummary: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            ticket_number: number;
            /** Format: uuid */
            property_id: string;
            /** Format: uuid */
            building_id: string;
            /** Format: uuid */
            unit_id: string;
            status: string;
            priority: string | null;
            category: string | null;
            symptom_summary: string | null;
            /** Format: date-time */
            submitted_at: string;
            /** Format: date-time */
            closed_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        TicketDetail: components["schemas"]["TicketSummary"];
        TicketListResponse: {
            items: components["schemas"]["TicketSummary"][];
            next_cursor: string | null;
        };
        Problem: {
            /**
             * Format: uri
             * @example urn:resident-os:problem:not-found
             */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
        };
    };
    responses: {
        /** @description No valid bearer token was provided. */
        AuthenticationRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A required dependency or the tenant context is unavailable. */
        DependencyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request or cursor could not be validated. */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested ticket does not exist or is not visible. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The caller exceeded the request limit. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Opaque keyset continuation token. Do not construct it. */
        TicketCursor: string;
        /** @description Number of tickets to return; the default is 50. */
        PageLimit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTickets: {
        parameters: {
            query?: {
                /** @description Opaque keyset continuation token. Do not construct it. */
                cursor?: components["parameters"]["TicketCursor"];
                /** @description Number of tickets to return; the default is 50. */
                limit?: components["parameters"]["PageLimit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page ordered by descending created_at and id. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            422: components["responses"]["InvalidRequest"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
}
